require: rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 120
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false


Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false
